### ISSUE TITLE
Feature not saved

### ISSUE THREAD

**Issue by guru1450** [Xposed-Modules-Repo/com.simo.tgramhooks#1]
Whenever i closed telegram and clear it from recent app some premium features are not applied like set emoji status change name colour etc i need to apply them every time. (Telegram v10.2.9)

**Comment by AvenCores** [comment]
Hey, you are trying to use server functions, they don't work due to limitations of Telegram itself (only local functions work).

**Comment by Syntaxerr101** [comment]
> Whenever i closed telegram and clear it from recent app some premium features are not applied like set emoji status change name colour etc i need to apply them every time. (Telegram v10.2.9)

You can't use forward option
But u can save any media and copy any texts
Also u are able to do screenshots inside
