### ISSUE TITLE
Can't make module built into app

### ISSUE THREAD

**Issue by moyun157** [Xposed-Modules-Repo/com.simo.tgramhooks#11]
I can't get the module built into the app using the lspatch framework.
![Screenshot_2024-05-06-02-03-38-034-edit_com estrongs android pop](https://github.com/Xposed-Modules-Repo/com.simo.tgramhooks/assets/85396220/9e978ca3-d642-4dea-8a74-23c984cd663c)
![IMG_20240506_024355](https://github.com/Xposed-Modules-Repo/com.simo.tgramhooks/assets/85396220/7413e815-4b5f-45aa-9fa6-027398f55ee8)

**Comment by Syntaxerr101** [comment]
Telegram has signature verification 
That why can't be installed inside lspatch
Am not familiar with lspatch try asking in the telegram group maybe someone has done it

https://t.me/TGramHooks_chat

**Comment by moyun157** [comment]
ok

**Comment by Syntaxerr101** [comment]
> ok

If u can install vphonegaga 
You can use Magisk and LSposed inside 
Full root environment with xposed framework support 
This version is free without ads
https://t.me/Android_Reverse/99

**Comment by tareq71ahmed** [comment]
Translate problem.  & if i canged translate into Bangla, After some times if i want to translate into English,The English option can't find. ps solve this

**Comment by Syntaxerr101** [comment]
Join chat then send screenshots 
I will check and fix that on next version 
https://t.me/TGramHooks_chat
