### ISSUE TITLE
Clients not responding...

### ISSUE THREAD

**Issue by harphere** [Xposed-Modules-Repo/com.simo.tgramhooks#5]
Running A14 Custom ROM on P8P with NekogramX using Kitsune 26.4 and [modded](https://github.com/mywalkb/LSPosed_mod) LSPosed. 

After enabling this module and selecting NekogramX, when I open NekogramX, I get a hanging app with nothing displayed. 

![Screenshot_20240406-140233_Nekogram X](https://github.com/Xposed-Modules-Repo/com.simo.tgramhooks/assets/28116390/bf9fd40b-f9eb-4c32-8276-292441486fc3)

**Comment by Syntaxerr101** [comment]
Hey! 
Mostly the reason is some old hooks, I will try update the module this week on my free time.

**Comment by Hammerhand17** [comment]
Same for me on Plus Messenger, OOS 14 on a OnePlus 12.

**Comment by Syntaxerr101** [comment]
> Same for me on Plus Messenger, OOS 14 on a OnePlus 12.

Hey!
There will be an update this week.
I will make sure to fix the issue and update hooks for all listed clients.

**Comment by alr86** [comment]
> > Same for me on Plus Messenger, OOS 14 on a OnePlus 12.
> 
> Hey! There will be an update this week. I will make sure to fix the issue and update hooks for all listed clients.

This week?!🤔🤔🤔

**Comment by Syntaxerr101** [comment]
> > > Same for me on Plus Messenger, OOS 14 on a OnePlus 12.
> > 
> > Hey! There will be an update this week. I will make sure to fix the issue and update hooks for all listed clients.
> 
> This week?!🤔🤔🤔

Well! Tonight there will be an update
