### ISSUE TITLE
Mdgram package name changed!!

### ISSUE THREAD

**Issue by ShaunCraft15** [Xposed-Modules-Repo/com.simo.tgramhooks#9]
Hello, i want to inform you about MDgram, after the 20.0 update the package named has been changed, i hope you update this, best telegram premium app ever, Free Palestine 🇵🇸🇵🇸

**Comment by Syntaxerr101** [comment]
Hey bro
I did update the package name in this module 
And removed the old one 
Can u check and confirm if the hook is working 
Thank you for your support bro ❤️
